### ISSUE TITLE
stddef.h not found

### ISSUE THREAD

**Issue by eberkund** [pedrosland/mmal-sys#4]
I am getting the following error when running with the "generate-bindings" feature.

```toml
# Cargo.toml
[target.'cfg(target_arch = "arm")'.dependencies]
mmal-sys = { git = "https://github.com/pedrosland/mmal-sys", features = ["generate_bindings"] }
```
I have installed clang according to the [bindgen docs](https://github.com/rust-lang-nursery/rust-bindgen/blob/master/book/src/requirements.md#debian-based-linuxes)

```txt
# apt-get install llvm-3.9-dev libclang-3.9-dev clang-3.9
```

But I get this error

```
error: failed to run custom build command for `mmal-sys v0.1.0-2 (https://github.com/pedrosland/mmal-sys#2a3abea2)`
process didn't exit successfully: `/home/erik/Code/otter/target/debug/build/mmal-sys-ad158f1538cb5b18/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-lib=mmal_core
cargo:rustc-link-lib=mmal_util
cargo:rustc-link-lib=mmal_vc_client
cargo:rustc-link-lib=vcos
cargo:rustc-link-lib=bcm_host
cargo:rerun-if-env-changed=HOST
cargo:rerun-if-env-changed=TARGET
cargo:rerun-if-env-changed=MMAL_INCLUDE_DIR
cargo:rerun-if-env-changed=MMAL_LIB_DIR
cargo:rustc-link-search=native=/home/erik/Code/otter/vc/lib

--- stderr
/usr/arm-linux-gnueabihf/include/stdlib.h:32:10: fatal error: 'stddef.h' file not found
/usr/arm-linux-gnueabihf/include/stdlib.h:32:10: fatal error: 'stddef.h' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```
